Numpy
- 넘파이의 기반 데이터 타입 : ndarray

In [87]:
import numpy as np

# ndarray
- .shape : array의 형태
- .dtype : data 값의 type

In [88]:
arr1 = np.array([1,2,3])
print('arr1 type : ', type(arr1))
print('arr1 array 형태 : ', arr1.shape)

arr1 type :  <class 'numpy.ndarray'>
arr1 array 형태 :  (3,)


In [89]:
arr2 = np.array([[1,2,3],
                 [4,5,6]])
print('arr2 type : ', type(arr2))
print('arr2 array 형태 : ', arr2.shape)

arr2 type :  <class 'numpy.ndarray'>
arr2 array 형태 :  (2, 3)


In [90]:
arr3 = np.array([[1,2,3]])
print('arr3 type : ', type(arr3))
print('arr3 array 형태 : ', arr3.shape)

arr3 type :  <class 'numpy.ndarray'>
arr3 array 형태 :  (1, 3)


In [91]:
print('arr1 : {:0}차원, arr2 : {:1}차원, arr3 :{:2}차원'.format(arr1.ndim, arr2.ndim, arr3.ndim))

arr1 : 1차원, arr2 : 2차원, arr3 : 2차원


In [92]:
lst1 = [1,2,3]
print(type(lst1))
arr1 = np.array(lst1)
print(type(arr1))
print(arr1)
print(arr1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3]
int32


# type 변경
- 연산의 특성상 같은 데이터 타입만 가능
- 다른 데이터 유형이 있으면 데이터 크기가 더 큰 데이터 타입으로 형 변환
- .astype() : type 변경

In [93]:
# int, string
lst2 = [1,2, 'test']
arr2 = np.array(lst2)
print(arr2, arr2.dtype)

# int, float
lst3 = [1,2,3.0]
arr3 = np.array(lst3)
print(arr3, arr3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [94]:
arr_int = np.array([1,2,3])
arr_float = arr_int.astype('float64')
print(arr_float, arr_float.dtype)

arr_int1 = arr_float.astype('int32')
print(arr_int1, arr_int1.dtype)

arr_float1 = np.array([1.1, 2.1, 3.1])
arr_int2 = arr_float1.astype('int32')
print(arr_int2, arr_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray 생성
- arange : 0부터 인자 값 -1 까지 값 순차적 생성
- zeros : 튜플 형태의 shape 값 입력하면 모든 값을 0으로 채워서 생성
- ones : 튜플 형태의 shape 값 입력하면 모든 값을 1로 채워서 생성

In [95]:
sequence_arr = np.arange(10)
print(sequence_arr)
print(sequence_arr.dtype, sequence_arr.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [96]:
zero_arr = np.zeros((3,2), dtype = 'int32')
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape, '\n')


one_arr = np.ones((3,2))
print(one_arr)
print(one_arr.dtype, one_arr.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2) 

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# reshape
- 차원과 크기 변경
- -1을 인자로 사용하면 더욱 효율적

In [97]:
arr1 = np.arange(10)
print('arr1:\n', arr1)

arr2 = arr1.reshape(2,5)
print('arr2:\n', arr2)

arr3 = arr1.reshape(5,2)
print('arr3:\n', arr3)

arr1:
 [0 1 2 3 4 5 6 7 8 9]
arr2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [98]:
# -1

arr1 = np.arange(10)
print('arr1:\n', arr1)

arr2 = arr1.reshape(-1,5)
print('arr2:\n', arr2)
print('arr2 shape:', arr2.shape)

arr3 = arr1.reshape(5,-1)
print('arr3:\n', arr3)
print('arr3 shape:', arr3.shape)

arr1:
 [0 1 2 3 4 5 6 7 8 9]
arr2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr2 shape: (2, 5)
arr3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
arr3 shape: (5, 2)


In [99]:
arr1 = np.arange(8)
arr3d = arr1.reshape((2,2,2))
print('arr3d:\n', arr3d.tolist())

# 3차원 -> 2차원
arr5 = arr3d.reshape(-1,1)
print('arr5:\n', arr5.tolist())
print('arr5 shape:', arr5.shape)

# 1차원 -> 2차원
arr6 = arr1.reshape(-1,1)
print('arr6:\n', arr6.tolist())
print('arr6 shape:', arr6.shape)

arr3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
arr5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arr5 shape: (8, 1)
arr6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arr6 shape: (8, 1)


# Indexing
- axis = 0 : row
- axis = 1 : column
   - 생략되면 axis = 0 의미
- 특정한 데이터만 추출
- 슬라이싱(Slicing) - : 사용
- 팬시 인덱싱(Fancy Indexing)
- 불린 인덱싱(Boolean Indexing)

## 단일값 추출

In [100]:
arr1 = np.arange(start=1, stop = 10)
print(arr1)

# 3번째 index 의미 (0부터 시작)
value = arr1[2]
print('value : ', value)
print(type(value))

[1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int32'>


In [101]:
# -1은 맨뒤 데이터 값을 의미
print(arr1[-1], arr1[-2])

9 8


In [102]:
# 값 변경
arr1[8] = 10
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

## 다차원에서 단일값 추출

In [103]:
arr1d = np.arange(start=1, stop = 10)
arr2d = arr1d.reshape(3,3)
print(arr2d)

print(arr2d[0,0])
print(arr2d[1,1])
print(arr2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
5
9


## slicing

In [104]:
arr1 = np.arange(start=1, stop=10)
arr3 = arr1[0:3]
print(arr3)
print(type(arr3))

[1 2 3]
<class 'numpy.ndarray'>


In [105]:
arr1 = np.arange(start=1, stop=10)
# 시작 인덱스 생략 : 처음부터 시작
arr4 = arr1[:3]
print(arr4)
# 종료 인덱스 생략 : 마지막까지
arr5 = arr1[3:]
print(arr5)
# 시작, 종료 인덱스 생략 : 전체
arr6 = arr1[:]
print(arr6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [106]:
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3,3)
print(arr2d, '\n')

print(arr2d[0:2, 0:2], '\n')
print(arr2d[0:2, 0:], '\n')
print(arr2d[0:2, :2], '\n')
print(arr2d[0:2, :], '\n')
print(arr2d[:, 0:2], '\n')
print(arr2d[:, :], '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2]
 [4 5]] 

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [4 5]] 

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [4 5]
 [7 8]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [107]:
print(arr2d, '\n')
print(arr2d[0], '\n')
print(arr2d[1], '\n')
print("shape : ", arr2d[1].shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3] 

[4 5 6] 

shape :  (3,)


## fancy indexing
- 리스트나 ndarray로 인덱스 집합 지정

In [108]:
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3,3)
print(arr2d, '\n')

arr3 = arr2d[[0,1], 2]
print(arr3.tolist(), '\n')

arr4 = arr2d[[0,1], 0:2]
print(arr4.tolist(), '\n')

arr5 = arr2d[[0,1]]
print(arr5.tolist(), '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[3, 6] 

[[1, 2], [4, 5]] 

[[1, 2, 3], [4, 5, 6]] 



## boolean indexing

In [109]:
arr1d = np.arange(start=1, stop=10)
print(arr1d, '\n')

print(arr1d>5)

[1 2 3 4 5 6 7 8 9] 

[False False False False False  True  True  True  True]


In [110]:
arr1d = np.arange(start=1, stop=10)
print(arr1d, '\n')

arr3 = arr1d[arr1d>5]
print(arr3)

[1 2 3 4 5 6 7 8 9] 

[6 7 8 9]


# 정렬
- 기본적으로 오름차순으로 정렬
- 내림차순 : [::-1]

> .sort
- np.sort() : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
- ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None

> .argsort : 
- 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스

## sort

In [111]:
org_arr = np.array([3,1,9,5])
print("원본 행렬 : ", org_arr, '\n' )

sort_arr1 = np.sort(org_arr)
print("정렬 행렬 : ", sort_arr1)
print("정렬 후 원본 행렬 : ", org_arr, '\n' )

sort_arr2 = org_arr.sort()
print("정렬 행렬 : ", sort_arr2)
print("정렬 후 원본 행렬 : ", org_arr)

원본 행렬 :  [3 1 9 5] 

정렬 행렬 :  [1 3 5 9]
정렬 후 원본 행렬 :  [3 1 9 5] 

정렬 행렬 :  None
정렬 후 원본 행렬 :  [1 3 5 9]


In [112]:
# 내림차순
sort_arr_desc = np.sort(org_arr)[::-1]
print(sort_arr_desc)

[9 5 3 1]


In [113]:
# 2차원 이상
arr2d = np.array([[8,12],
                 [7,1]])
print(arr2d,'\n')

sort_arr2d_axis0 = np.sort(arr2d, axis=0)
print('로우 방향으로 정렬:\n', sort_arr2d_axis0, '\n')

sort_arr2d_axis1 = np.sort(arr2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_arr2d_axis1)

[[ 8 12]
 [ 7  1]] 

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]] 

컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


## argsort
- 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스

In [114]:
org_arr = np.array([3,1,9,5])
sort_indices = np.argsort(org_arr)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 : ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 :  [1 0 3 2]


In [115]:
# 내림차순으로 정렬했을 때
org_arr = np.array([3,1,9,5])
sort_indices = np.argsort(org_arr)[::-1]
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 : ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 :  [2 3 0 1]


In [116]:
# 매우 활용도가 높음
# 예시
name_arr = np.array(['Park', 'Kim', 'Lee', 'Jung', 'Baek'])
score_arr = np.array([95, 78, 68, 83, 97])

sort_indices_asc = np.argsort(score_arr)
print("성적 오름차순 정렬 시 score_arr의 인덱스 : ", sort_indices_asc)
print("성적 오름차순으로 name_arr의 이름 출력 : ", name_arr[sort_indices_asc])


성적 오름차순 정렬 시 score_arr의 인덱스 :  [2 1 3 0 4]
성적 오름차순으로 name_arr의 이름 출력 :  ['Lee' 'Kim' 'Jung' 'Park' 'Baek']


# 선형대수 연산
- 행렬 내적 : np.dot()
- 전치 행렬 : trnaspose()

## 내적

In [117]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

In [118]:
dot_product = np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


## 전치

In [119]:
A = np.array([[1,2,3],
             [4,5,6]])
A_transpose = np.transpose(A)
print(A, '\n\n', A_transpose)

[[1 2 3]
 [4 5 6]] 

 [[1 4]
 [2 5]
 [3 6]]
